/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NurseRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patients;
import Business.Patient.PatientsDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;

/**
 *
 * @author vaibh
 */
public class PatientDetailsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form PatientDetailsJPanel
     */
    public PatientDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        valueLabel.setText(enterprise.getName());
        
        populateDocComboBox();
        
    }
    
    public void populateDocComboBox(){
        DocjComboBox1.removeAllItems();
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof DoctorOrganization){
                for(Employee emp : organization.getEmployeeDirectory().getEmployeeList()){
                    DocjComboBox1.addItem(emp);
                }
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NamejTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AgejTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        WeightjTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PulsejTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RRatejTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TempjTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BPressurejTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CNSjTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BackjButton1 = new javax.swing.JButton();
        SavejButton2 = new javax.swing.JButton();
        DocjComboBox1 = new javax.swing.JComboBox();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<value>");

        jLabel1.setText("Name :");

        jLabel2.setText("Age :");

        jLabel3.setText("Weight :");

        jLabel4.setText("Pulse :");

        jLabel5.setText("Respiratory Rate :");

        jLabel6.setText("Temperature :");

        jLabel7.setText("Blood Pressure :");

        jLabel8.setText("CNS :");

        jLabel9.setText("Doctor :");

        BackjButton1.setText("<< Back");
        BackjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButton1ActionPerformed(evt);
            }
        });

        SavejButton2.setText("Save");
        SavejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavejButton2ActionPerformed(evt);
            }
        });

        DocjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RRatejTextField2)
                                .addComponent(TempjTextField1)
                                .addComponent(BPressurejTextField1)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(CNSjTextField2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(DocjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PulsejTextField1)
                                .addComponent(WeightjTextField1)
                                .addComponent(AgejTextField1)
                                .addComponent(NamejTextField1)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(BackjButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                            .addComponent(SavejButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(valueLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AgejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(WeightjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PulsejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RRatejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TempjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(BPressurejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CNSjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(DocjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackjButton1)
                    .addComponent(SavejButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SavejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavejButton2ActionPerformed
        // TODO add your handling code here:
        PatientsDirectory po = null;
         Patients patients = null;
        try{
        if(!NamejTextField1.getText().isEmpty() || !AgejTextField1.getText().isEmpty() || 
                !WeightjTextField1.getText().isEmpty() || !PulsejTextField1.getText().isEmpty() || !TempjTextField1.getText().isEmpty()
                || !RRatejTextField2.getText().isEmpty() || !BPressurejTextField1.getText().isEmpty() 
                || !CNSjTextField2.getText().isEmpty()){
              
       
        String username = "";
        //PatientsDirectory po = null;
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof PatientOrganization){
                patients = organization.getPatientsDirectory().createPatients();
                po = organization.getPatientsDirectory();
            }
        }
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof DoctorOrganization){
                for(Employee dir : organization.getEmployeeDirectory().getEmployeeList()){
                    if(DocjComboBox1.getSelectedItem().toString().equals(dir.getName())){
                        username = dir.getUserName();
                    }          
            }
        } 
        }
        
        patients.setName(NamejTextField1.getText());
        patients.setAge(Integer.parseInt(AgejTextField1.getText()));
        patients.setWeight(Integer.parseInt(WeightjTextField1.getText()));
        patients.getVitalRecords().setPulse(Integer.parseInt(PulsejTextField1.getText()));
        patients.getVitalRecords().setTemperature(Integer.parseInt(TempjTextField1.getText()));
        patients.getVitalRecords().setrRate(Integer.parseInt(RRatejTextField2.getText()));
        patients.getVitalRecords().setBloodPreassure(BPressurejTextField1.getText());
        patients.getVitalRecords().setCnsExam(CNSjTextField2.getText());
        patients.setAssignedDoc(DocjComboBox1.getSelectedItem().toString());
        patients.setAssignedDocUsername(username);
        
        NamejTextField1.setText("");
        AgejTextField1.setText("");
        WeightjTextField1.setText("");
        PulsejTextField1.setText("");
        TempjTextField1.setText("");
        RRatejTextField2.setText("");
        BPressurejTextField1.setText("");
        CNSjTextField2.setText("");
        populateDocComboBox();
        
        } else{
            JOptionPane.showMessageDialog(null, "Fields cannot be left blank!");
            po.removePatients(patients);
    }
        }
        catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null, "Please enter values in digits where required!");
             po.removePatients(patients);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong. Please try again!");
             po.removePatients(patients);
        }
    }//GEN-LAST:event_SavejButton2ActionPerformed
    
    private void BackjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NurseWorkAreaJPanel nwjp = (NurseWorkAreaJPanel) component;
        nwjp.populatePatientsTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackjButton1ActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgejTextField1;
    private javax.swing.JTextField BPressurejTextField1;
    private javax.swing.JButton BackjButton1;
    private javax.swing.JTextField CNSjTextField2;
    private javax.swing.JComboBox DocjComboBox1;
    private javax.swing.JTextField NamejTextField1;
    private javax.swing.JTextField PulsejTextField1;
    private javax.swing.JTextField RRatejTextField2;
    private javax.swing.JButton SavejButton2;
    private javax.swing.JTextField TempjTextField1;
    private javax.swing.JTextField WeightjTextField1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
